import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TableProvider } from "./providers/contextProvider";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TableProvider>
         <main className="relative">
        <Navbar />
        <div className="flex">
          <Sidebar />
          <section className="min-h-screen overflow-y-scroll"  style={{ width: "calc(100vw - 64px)", marginLeft: "64px" ,marginTop:'64px'}}>
            <div className="w-full">{children}</div>
          </section>
        </div>
      </main>
        </TableProvider>
      </body>
    </html>
  );
}

